---
title: "Response to reviewers"
author: "Zach Garfield"
date: "3/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Response to editor and reviewer comments

### Editor comments

**Statistical reporting and further analysis: The GLMM should be reported in full somewhere.**

The GLMM is actually 109 GLMMs (one for each coded variable). We now include a table of all GLMM coefficients in the SI.

**This could go in the supplemental materials. However, can we learn more from it? Do the random effects matter for the ethnographers?* **

We now report random effects for ethnographer and culture, and also plot the SDs.

**What about the national origin effects for the ethnographers? We recommend taking seriously the reflexive analytical techniques of putting the ethnographer in the analysis (see work by Robert Aunger working in the Congo Basin). Does the ethnographer matter? If so, how much?**

Although we determined the gender of almost all ethnographers (see below), we were not able to confirm the national origins of most.

**Further, and we realize there may not be sufficient power for this, but does the gender of the ethnographer predict ‘seeing’ female leaders in a population? This can (potentially) speak quantitatively to some of the qualitative discussion about limitations and biases in the approach.**

We determined the gender of almost all authors of all documents included in our study. We found that of the 884 text records with no female author or co-author, 21 (2.4%) reported female leadership. Of the 225 text records with a female author or co-author, 20 (8.9%) reported female leadership, suggesting that female ethnographers were more likely to report female leaders. After accounting for the non-independence of text records (i.e., multiple records from the same document) using a logistic mixed effects regression model, however, we found that although there was a positive effect of co-author gender on reporting female leadership (OR = 3.5), it was not statistically significant (p = 0.25). We now report this in our results section.

**Could further analyses be done to obtain more information on the nature of the variation within the data?**

In the original version of the ms we did not describe our numerous efforts at dimension reduction, including various flavors of logistic PCA, non-negative matrix factorization (NMF), and various flavors of cluster analysis, and we regressed the resulting components against our various culture-level variables. These initial efforts did not yield much convincing "structure" in our data or results beyond what we reported. We now briefly describe these efforts so as to better contextualize the results that we do report, and we report logisticPCA and NMF results in the SI.

We now report on the dimensionality reduction that did produce stable and interpretable clusters and incorporate these "features" of leadership into our analyses and conclusions. See below. 

**1.	The cluster analysis is nice, but it opens up the option to combine items within both qualities and functions to create a smaller number of higher-level categories or codes that, arguably, are better measured. The issue here is that some things that don’t appear frequently might rise in frequency when they are combined with other similar items. Suppose you use a higher-level category that contains 4 codes and you code the society as ‘1’ if any of the codes appears and zero otherwise. In our view, you need not go crazy with this approach, but look for any tightly bound clusters and consider pursuing those. If you are able to do this, the presentation could be more compact and easier to digest for the reader.**

We now additionally create "feature" variables based on the clusters we did find, and investigate their relationship to our four predictor variables (i.e., our four factors).

**2.	Why not take either some of your original codes or some of these higher-level codes (from the above cluster analysis) and regress them on societal-level features related to subsistence type (foragers, pastoralist, etc. or simply forager vs. non-forager if that’s appropriate), levels of jurisdictional hierarchy (or other measures of societal complexity), population size, and potentially ecological variables. Your sample is not big, but you might be able to get some juice out of this. If interesting findings do emerge, you should consider adding or otherwise altering your visualizations.**

See above. We now include some additional plots in the SI.

**3.	Be clearer about how you are accounting for research effort in each society. For example, are you controlling for the total number of words or pages for each population?**

We incorporate total number of pages of ethnography for each culture. Results now reported.

**This seems very important since we want to make sure that the variation observed isn’t due to some populations getting more or less total study effort or writing effort.**

We investigated three possible sources of bias: total number of pages of ethnography, year of publication of each document, and the presence or absence of a female author/co-author for each document. We found evidence for bias in reporting of evidence for 9 of 109 variables based on year of publication only. There was no convincing evidence of bias in any variable based on the total number of pages of ethnography or ethnographer gender. Results now reported.

**4.	Did you control for observation year? This might be too highly correlated with ethnographer identity, but worth checking**

Yes. See above.

**5.	Phylogenetic controls. While this is the probability sample, worries persist about non-independence (see R1). There are a variety of approaches to mitigate (and study!) this. Is there any clumping among related groups that cannot be explained by other variables? Do the patterns hold when you either control for linguistic distance or cluster in some way (continental fixed effects at a minimum)?**

We agree that worries persist about the putative independence of the PSF. We now investigate continental effects for each variable. As we now report, continental region is confounded with subsistence strategy, so we fit models of all variables as functions of subsistence and region. After correcting p-values for a false discovery rate of 0.05, we found that 2 of our variables -- Moral authority and Prosocial investment -- varied significantly by region. We now report these effects.

**6.	Analyze the degree to which ‘researcher efforts’ (say measured by total words on that society and/or number of paragraphs on leadership) predict the appearance of a code. For example, what if the total ethnographic pages strongly predict the the appearance of “high status” as a code. Suppose the 10% of populations who don’t mention “high status” hardly wrote anything about leadership. On the other hand, if for other traits, there’s no relationship between researcher effort and appearance, then a case can be made that absence of evidence could very well be evidence of absence.**

As discussed above, we investigated the possible effects of total number of pages of ethnography for each culture on each variable. As we now report, we found no significant effects.

**We recommend making liberal use of supplemental materials. Some of the analyses may not yield findings of sufficient interest to warrant placement in the main text, but some readers may want to have a look at them, so put them in the supplemental and briefly mention them in the main.**

We have expanded our supplemental materials considerably.

**Returning to the WEIRD Problem: in your discussion, please circle back to the question of what research might be missing by focusing on leadership in Western or industrialized societies. Say more on how leaders in small-scale societies are the same and different—and perhaps you will be able to explain some of that variation with variables like jurisdictional hierarchy or subsistence type or mobility measures. As mentioned by R1, this likely involves returning to the GLOBE data and putting it together with your findings more directly.** 

We agree we need to better situate our study within the theme of the special issue. We interpret "Beyond WEIRD" in the following way: The original WEIRD paper was a needed wake-up call for psychology. However, we now worry that many psychologists are operationalizing WEIRD as a dichotomy: WEIRD vs. non-WEIRD. This is obviously a mistake, as there is enormous variation among the non-WEIRD. Our data set focuses primarily on traditional societies, and thus speaks to variation among the non-WEIRD, a point we now emphasize. At the same time, as Edward Said famously argued, anthropologists tend to make the opposite mistake: exoticizing the "Other" relative to the "West". 

We have revised our introduction section, the discussion, and our conclusion along these lines. We hope we have struck the right balance in identifying important common themes and patterns across most of the populations in our data, while doing justice to their differences.

**Status vs. Leadership: R2 asks about status vs. leadership. Given recent debates about a “leadership psychology” as distinct and separable from status psychologies (like prestige and dominance, van Vugt), it might be worth expanding a bit on what these data say about the connection between status and leadership.** 

This is a good idea. We now include a short section on our "status" variable, and what distinguishes leadership records with evidence for social status from those without such evidence. We found a small set of words, such "respect", "prestige", and "honor", that were significant predictors of "high status" leaders. We found a weak effect of group structure on evidence for high status, and moderate effects of subsistence strategy and continental region. We now report these results. And following this approach (an in response to other comments by reviewers) we report similar analyses for coercive authority and shamanism. 

**Expanding the dataset: the natural next step with this project is to use this small sample of hand coded categories to create an automated approach for all of the eHRAF, perhaps based on key words. The idea is to develop a set of keywords or other patterns that reliably predict when a paragraph should be coded in a particular way. The method can be developed and benchmarked using the dataset you’ve created and then simply applied in automated fashion to the entire eHRAF corpus. We offer this as a suggestion, but realize that it’s a lot to ask in this context.** 

This is a good suggestion for future research, but goes beyond remit of the current paper.

**Finally, the reviewers made a number of valuable suggestions, not enumerated above,  that should help you sharpen you presentation and discussion. Please attend to those.**

## Reviewer 1 comments

**This manuscript presents a descriptive analysis of the HRAF to provide information about leadership in traditional societies. Overall, I enjoyed reading the paper and thought it was a useful resource. It provides a comprehensive analysis of leadership across a wide swath of traditional cultures. It reports on the types of functions leaders serve, the qualities possessed by leaders, and the costs and benefits of leadership experienced by both leaders and followers. The paper will likely be of interest to anyone working in the area of leadership, social hierarchy, or group behavior. I provide some comments below aimed at helping the authors increase the potential accessibility and impact of the work.** 

We greatly appreciate the detailed comments and very useful suggestions. 

**The paper was framed partially as providing an analysis of differences between traditional societies and WEIRD societies but, unless I missed it, there was not much analysis along these lines. Neither the background section nor the Discussion section focuses much on contrasting WEIRD and traditional societies. The paper appears to miss out on a useful opportunity to provide some commentary on this issue. Also, I realize the paper is decidedly exploratory/descriptive, but did the authors have any hypotheses about differences between WEIRD and traditional societies?** 

We have now greatly revised our manuscript and more clearly explain that our exploratory analyses aim to uncover variation (or lack of variation), within "non-WEIRD" populations. We do briefly review relevant perspectives on leadership in WEIRD contexts (primarily in the introduction and to a lesser degree in our interpretations of results), but we do not aim to compare WEIRD and non-WEIRD leadership dynamics. 

We did not have any predictions and now more clearly state this. 

**The paper suggests that one of the most important qualities and benefits of being a leader involves being of "high status." That's a little dissatisfying. What's the difference between being high status and being a leader? I realize the authors provided brief operational definitions of the two constructions, but might they simply be two ways of describing the same thing (having a high degree of influence)? Perhaps the authors could do just a bit more to differentiate them.** 

We have substantially revised the manuscript and analyses regarding this point. We now include specific sections in the results, discussion, and SI which are focused on the relationship between leadership and high social status and we believe our empirical results here fit in well with much of the current evolutionary leadership literature. 

**Some of the benefits of leadership also appear as costs. Greater reflection and explanation on this aspect of the data seems warranted. I understand that leaders can enjoy certain benefits (access to resources) but then if they lose their status as leader they might lose those benefits (if someone falls from grace, they no longer get a larger piece of the pie). Do the findings reflect anything more complex than that? Their discussion of benefits of costs was brief and a little disappointing. The paper might benefit from enhancing that discussion.** 

We have also substantially revised our analyses of the costs and benefits of leadership, including in the results and in our interpretations. We compare the relative evidence for leader and follower benefits vs. costs in the manuscript and provide exploratory models on the total leader benefits and costs in the SI. 

**Some readers might appreciate a bit more detail about how the HRAF database was created, including how the ethnographic records were identified and selected and whom and when they are from.** 

We added additional details in the methods section on the eHRAF and ethnographic sample and now more clearly direct readers to the original publication from which the database was built, which includes additional details. 

We also include additional details in the results and supplementary information on the corpus of ethnographic documents which provide the sample of ethnographic paragraphs.

**I don't work with ethnographic data, so perhaps this question is naïve, but: What conclusions can we draw about the actual frequency of leadership functions and traits from the frequency with which they are mentioned in the ethnographic record? There is an implicit assumption that the two are closely aligned. Has such an alignment been confirmed? Is that even testable?**

The reviewer brings up an important point. We now are more careful to frame our results as "evidence for" or "lack of evidence for" leadership traits in each culture, and to make clear that absence of evidence is not evidence of absence.

Also, this is partly our motivation for representing the percentage of cultures which provide at least one text record supporting each of the operationalized variables. Despite this low threshold for accepting supporting evidence, the ethnographic record (sampled here) does not provide support for every variable from every culture. At this culture-level we feel more confident our data provide a estimate of cross-cultural frequency, albeit an inherently noisy, "course-grained" estimation. As a further supporting point, the field of ethnology (the branch of anthropology focused on comparing characteristics of populations across the globe) is based on developing comparable and often quantitative measures from primary ethnographic information. For example, the Ethnographic Atlas, which provides hundreds of coded quantitative and qualitative variables on thousands of cultures and the Standard Cross-Cultural Sample, which provides thousands of coded quantitative and qualitative variables on 186 cultures, were developed in essentially the same way we have developed our operationalized, researcher-coded variables here. Developing and contrasting coded measures from primary ethnographic documents is not without limitations, but does represent (perhaps) the only method to systematically and empirically compare measures across a large sample of cultures/populations. At the text-record level drawing strong conclusions about the actual frequency of traits is slightly more problematic (especially the absence of relative infrequency). However, fundamentally these results provide a systematic view of the ethnographic record on these measures. Our intention is that from our results field researchers and theoreticians interested in these topics can draw inference from a more comprehensive view of human cultural diversity rather than haphazardly self-selecting and relying on only a handful of ethnographic cases studies.

We now discuss these limitations and points more clearly in the limitations section.

**What does it mean for someone to be a leader at the "supracommunity" level? I'm not familiar with the term, so had difficulty contextualizing the relevant findings. And how exactly do the authors define "community" versus "supracommunity"?**

In the methods section we now include a description of all levels of our *group structure* coding to clearly explain this coding scheme. We coded supracommunity leaders in cases when the "group" involves leadership beyond the community level and across multiple residential communities, such as regional political leaders, chiefs in complex chiefdoms, kings, and state-level leaders. This terminology was vaguely inspired by Murdock and Provost's (1971) Political Integration Scale which codes the political integration at the society-level as either autonomous local communities, or having one, two, or three levels of jurisdictional hierarchy "above the community"; i.e., if political authority is exclusive to a local village headman, the group would be coded as "autonomous" but if the village and headman are under authority of a chief from a separate community, the group would be coded as "one level above community", and so forth. 

## Reviewer 2 comments

**The authors present results of a Herculean task of mining the ethnographic record to estimate frequency of and covariation between functions, qualities, and costs/benefits of leadership. While the study itself is exploratory, it will be very useful to future work testing models of the evolution of leadership and social inequality in general. I have a number of suggestions and comments that may improve the paper, none highly critical:**

We greatly appreciate the detailed comments and very useful suggestions. 

**The abstract could be tightened up in terms of description of particular costs and benefits to leaders and followers. And a brief justification in the abstract for why the study compares costs and benefits would be useful- e.g. understanding evolution of leader or follower strategies requires understanding the (fitness-relevant) costs and benefits to them.**

Good point. [Need to do]

**Lines 88-89 suggest that the paper's ethnographic analysis will include leadership at all levels of social organization. But does the theory and analysis reported in the paper really extend to all levels of social organization- such as child play groups or households? It seems the focus is still community-level cooperation among adults. Perhaps clarify.**

This statement in the introduction is intended to apply across disciplines focused on leadership dynamics and not specifically apply to the methods of the current study. The reviewer brings up a well-received point, however. Any work in developmental psychology on social hierarchy and leadership would not be subject to this critique. We have now rephrased this claim to better fit with our specific objectives and outcomes.

**In the "Functions of leadership" section, I would expand on your claim that leadership emerges when there is demand for a "managerial presence". You might describe collective action or coordination problems here. That might better motivate the subsequent discussion of different functions of leadership in small-scale societies, as well as discussion of the conditions (e.g. demographic change, wealth access) that increase institutionalization or authority of leaders. Glowacki and von Rueden (2015) suggest that inter-family conflict resolution is where leader institutionalization often first arises, and Roscoe (2009) makes a similar argument concerning leadership in highland New Guinea, where the institutionalized display of material wealth organized by Big Men is rewarded more than ad hoc leadership during war.**

We now more clearly motivate our discussion of the functions of leaders and link discussions to these sources and ideas. 
**The Wofford study (lines 214-233) and GLOBE study reminds me of the vast array of descriptive models in leadership/managerial studies- transactional vs. transformational leadership and their sub-components being one of the most popular. So what should a reader make of this literature, with respect to evolution of leadership in small-scale societies? Do bureaucracies, formal legal systems, formal education-based skills, and large inequalities in remuneration limit universality of descriptive models from leadership/managerial studies? I'd be more explicit on this in the introduction.**

We now include additional discussion of managerial frameworks of leader behavior and highlight recent approaches that are more conducive to coupling with evolutionary and anthropological/psychological approaches. 

**For the discussion section: how does your own descriptive modeling of leadership in traditional societies agree or not with Wofford or other models from large-scale societies?**

We now include a paragraph in our concluding statement interpreting our overall findings in reference to Wofford's and GLOBE study results, i.e., attempting (albeit briefly) to tie in our (non-WEIRD) results to relevant findings from WEIRD settings. 

**There is little mention of gender in the Qualities of leadership section, even though this might be first attribute an alien might recognize as covarying with community-level leadership in human societies. Even in the more egalitarian societies, men often wield more overt political influence during camp or band-wide political discussions. Without getting into arguments about patriarchy and its origins, it might at least be useful to cite your own work on Chabu and work on the Tsimane (von Rueden et al. 2018) that finds similar traits predict leadership for men and women, implying its not gender per se that gives men a leadership advantage in politics.**

We now discuss sex-differences in community and political leadership, and reference in greater details (albeit brief) the universal male bias in community leadership in the introduction and cite these works. We also include specific sections on female leadership and sex differences in the results and discussion.

**How often are shamans also the most influential political figure (given your suggestion in line 317)? My sense from various ethnographies is that this was not the majority of cases (though often the case), whether in more egalitarian societies or chiefdoms. I could be wrong.** 

We did not mean to imply shamans are often the *most* influential political leaders in this passage, only that managerial elites (e.g., Stanish) are often associated with a special social status rooted in ideology. However, to this point we have now include a dedicated section in the results section to shaman leaders and directly address the reviewer's inquires. As we discuss, we see shamanism as a potentially important and overlooked leadership strategy. 

**Even though this paper is more exploratory, in the last section before the methods, can you venture any predictions about leader function-leader quality covariation? Or about how reported costs and benefits of leadership and followership may vary depending on subsistence type?**

We explicitly avoided making any predictions. We understand that our review of existing evidence and theory could be used to generate a number of predictions. But ultimately, our empirical goals are simply to explore the data structure rather than test predictions. We now more make this point more clearly. 

**Many of the variables coded as qualities of leaders may also fall under leader costs and benefits, e.g. polygyny, physical health, wealthy. Were variables like these analyzed in both cases?**

The reviewer brings up an important point, i.e., the conceptual and operational overlap in many study variables, and specifically between various qualities and benefits. This is partly a consequence of our methodology, given the coding of qualities was purely driven by the ethnographic record whereas our coding of costs and benefits was sketched out a priori, based on evolutionary theory. 

Concerning the quality of *polygynous* and the benefit of *mating*, note that the *mating* benefits includes polygyny, but also includes other mating benefits, such as having a higher quality spouse (but only one). Indeed every text recorded coded as providing evidence for the quality of *polygynous* also provides evidence for the leader *mating* benefit, however the inverse is not the case. Therefore these variables are in fact distinct. 

Another aspect of potential overlap in the data is the quality *wealthy* and the benefit *material resources*. Here, note the operationalization of the quality *wealthy* suggests a relative comparison to followers, or a qualifying statement (we have slightly adjusted the phrasing in our table of operationalization). The benefit measures however is focused on the transactional nature of resource transfer or 'payment'. 

We now discuss these distinctions in more detail in the methods and limitations sections.
<!-- NEED TO DO ABOVE? -->

**Can you control for phylogeny (e.g. linguistic affinity). See Minocher et al. 2019 in Evolution and Human Behavior. It may be that covariation you detect between qualities and leader functions is driven by shared cultural history more than direct causal relationship between qualities and leader functions.**

We appreciate this point, however as mentioned above, we did not incorporate proper phylogenetic controls. The PSF as a stratified random sample provide some safeguards against effects of non-independence, although not perfectly. We do now include significant additional analyses more systematically including and reporting continental region and subsistence strategy effects as control measures. We also now report the GLMM for each of our researcher-coded variables which includes random effects for author nested within culture and we report on possible sources of biases in the SI.

**Can you report text records pertaining to male vs. female leadership by subsistence type (lines 966-982)?**

We now report that the majority of female leader-exclusive text records were from horticulturalists (76%) and provide a table of text records by leader sex and subsistence in the SI. 

**While your analysis strategy was not designed to test particular predictions, I'd be very interested to see you report how the authority variable covaries with different leader functions in different subsistence types, which has relevance to institutionalization of leadership and evolution of social inequality.**

We now include a section in the results focused on better understanding variation with the coercive authority measure. 

**Give more explanation of prestige theory and computational services theory (lines 1279-1280), including what different predictions they make.**

We now briefly (but in greater detail then our initial submission) discuss the prestige and computational services theories and interpret our empirical results in reference to these two theories. See the discussion section on "Beyond dual models."

**Followers in many cases may be making best of limited options, particularly in societies with steeper hierarchy. So I'm not sure benefits of followership must outweigh the costs (1414-1415) in same way as for leadership.**

We completely agree. This statement was intended to be in reference to a priori assumptions on the evolution and emergence of leader-follower dynamics, similar to discourse on the conundrum of the evolution of cooperation. Though, clearly, in particular circumstances an individual will cooperate when doing so incurs a cost just as followers in particular circumstances will follow when doing so incurs a cost. We assume that over evolutionary history and for leader-follower dynamics to be selected for, both leaders and followers would have to receive benefits on average, over time. 

We have revised this statement.




